//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFMapper {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AFMapper.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No command string defined in translator for command {0}. ähnelt.
        /// </summary>
        internal static string DBTRANS_NOCOMMANDDEFINED {
            get {
                return ResourceManager.GetString("DBTRANS_NOCOMMANDDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GetReader is not available. ähnelt.
        /// </summary>
        internal static string ERR_GETREADER_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("ERR_GETREADER_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type does not contain a primary key field. ähnelt.
        /// </summary>
        internal static string ERR_TYPE_DOES_NOT_CONTAIN_KEY {
            get {
                return ResourceManager.GetString("ERR_TYPE_DOES_NOT_CONTAIN_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transaktion kann nicht abgeschlossen werden. Es ist keine Transaktion aktiv. ähnelt.
        /// </summary>
        internal static string ERROR_CANTCOMMITNOACTIVETRANSACTION {
            get {
                return ResourceManager.GetString("ERROR_CANTCOMMITNOACTIVETRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transaktion kann nicht abgeschlossen werden. Es ist keine Transaktion aktiv. ähnelt.
        /// </summary>
        internal static string ERROR_CANTROLLBACKNOACTIVETRANSACTION {
            get {
                return ResourceManager.GetString("ERROR_CANTROLLBACKNOACTIVETRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transaktion kann nicht gestartet werden. Es ist bereits eine Transaktion aktiv. ähnelt.
        /// </summary>
        internal static string ERROR_CANTSTARTTRANSACTIONWHILETRANSACTIONEXIST {
            get {
                return ResourceManager.GetString("ERROR_CANTSTARTTRANSACTIONWHILETRANSACTIONEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Methode {0} muss als public static definiert sein, um als COMMAND verwendet werden zu können. ähnelt.
        /// </summary>
        internal static string ERROR_COMMANDMETHODMUSTBESTATIC {
            get {
                return ResourceManager.GetString("ERROR_COMMANDMETHODMUSTBESTATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while commit a transaction. ähnelt.
        /// </summary>
        internal static string ERROR_COMMITTRANSACTION {
            get {
                return ResourceManager.GetString("ERROR_COMMITTRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while commit transaction. See Innerexception for more informations. ähnelt.
        /// </summary>
        internal static string ERROR_COMMITTRANSACTION1 {
            get {
                return ResourceManager.GetString("ERROR_COMMITTRANSACTION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Constructor kann nicht ohne Angabe der Datenbank verwendet werden. ähnelt.
        /// </summary>
        internal static string ERROR_DBCONSTRUCTORCANTUSEDWITHOUTPARAMETER {
            get {
                return ResourceManager.GetString("ERROR_DBCONSTRUCTORCANTUSEDWITHOUTPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transaction allways exist. ähnelt.
        /// </summary>
        internal static string ERROR_DBTRANSACTIONEXISTS {
            get {
                return ResourceManager.GetString("ERROR_DBTRANSACTIONEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already an open transaction. A new transaction cannot be created. ähnelt.
        /// </summary>
        internal static string ERROR_DBTRANSACTIONEXISTS1 {
            get {
                return ResourceManager.GetString("ERROR_DBTRANSACTIONEXISTS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Löschen wurde abgebrochen. ähnelt.
        /// </summary>
        internal static string ERROR_DELETECANCELED {
            get {
                return ResourceManager.GetString("ERROR_DELETECANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Verzeichnis &apos;{0}&apos; befindet sich nicht auf einem physischen Laufwerk sondern repäsentiert ein UNC-Verzeichnis, für das keine Seriennummer verfügbar ist. ähnelt.
        /// </summary>
        internal static string ERROR_DIRECTORYINFO_NOPHYSICALDRIVE {
            get {
                return ResourceManager.GetString("ERROR_DIRECTORYINFO_NOPHYSICALDRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ {0} enthält kein Systemfeld für PrimaryKey. IsUnique wird deshalb nicht unterstützt. ähnelt.
        /// </summary>
        internal static string ERROR_ISUNIQUENOTAVAILABLE {
            get {
                return ResourceManager.GetString("ERROR_ISUNIQUENOTAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ {0} hat keine Eigenschaft mit dem Namen {1}, an die gebunden werden kann. (GET fehlt) ähnelt.
        /// </summary>
        internal static string ERROR_MISSINGBINDINGGETTER {
            get {
                return ResourceManager.GetString("ERROR_MISSINGBINDINGGETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ {0} hat keine Eigenschaft mit dem Namen {1}, an die gebunden werden kann. (SET fehlt) ähnelt.
        /// </summary>
        internal static string ERROR_MISSINGBINDINGSETTER {
            get {
                return ResourceManager.GetString("ERROR_MISSINGBINDINGSETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feldname für Summierung nicht angegeben. ähnelt.
        /// </summary>
        internal static string ERROR_MISSINGFIELDNAME {
            get {
                return ResourceManager.GetString("ERROR_MISSINGFIELDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ {0} verfügt über kein Feld, dass mit der Eigenschaft eSystemFieldFlag.key versehen ist. ähnelt.
        /// </summary>
        internal static string ERROR_MISSINGKEYFIELD {
            get {
                return ResourceManager.GetString("ERROR_MISSINGKEYFIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ/die Klasse {0} enthält kein Feld, das als PrimaryKey gekennzeichnet ist (Attribut Field). ähnelt.
        /// </summary>
        internal static string ERROR_MISSINGPRIMARYKEY {
            get {
                return ResourceManager.GetString("ERROR_MISSINGPRIMARYKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ {0} ist weder mit dem Attribut TABLE noch mit dem Attribut VIEW versehen. ähnelt.
        /// </summary>
        internal static string ERROR_MISSINGTABLEATTRIBUTE {
            get {
                return ResourceManager.GetString("ERROR_MISSINGTABLEATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ/die Klasse {0} enthält kein Feld, das als TimestampChanged gekennzeichnet ist (Attribut Field). ähnelt.
        /// </summary>
        internal static string ERROR_MISSINGTIMESTAMPCHANGED {
            get {
                return ResourceManager.GetString("ERROR_MISSINGTIMESTAMPCHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ/die Klasse {0} enthält kein Feld, das als TimestampCreated gekennzeichnet ist (Attribut Field). ähnelt.
        /// </summary>
        internal static string ERROR_MISSINGTIMESTAMPCREATED {
            get {
                return ResourceManager.GetString("ERROR_MISSINGTIMESTAMPCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde keine Typbeschreibung (TypeDescription) übergeben. ähnelt.
        /// </summary>
        internal static string ERROR_MISSINGTYPEDESCRIPTION {
            get {
                return ResourceManager.GetString("ERROR_MISSINGTYPEDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konfiguration muss vom Typ cr2.data.FirebirdConfiguration sein. ähnelt.
        /// </summary>
        internal static string ERROR_MUSTBEFIREBIRDCONFIGURATION {
            get {
                return ResourceManager.GetString("ERROR_MUSTBEFIREBIRDCONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translator muss vom Typ cr2.data.FirebirdTranslator sein. ähnelt.
        /// </summary>
        internal static string ERROR_MUSTBEFIREBIRDTRANSLATOR {
            get {
                return ResourceManager.GetString("ERROR_MUSTBEFIREBIRDTRANSLATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konfiguration muss vom Typ cr2.data.PostgreConfiguration sein. ähnelt.
        /// </summary>
        internal static string ERROR_MUSTBEPOSTGRECONFIGURATION {
            get {
                return ResourceManager.GetString("ERROR_MUSTBEPOSTGRECONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translator muss vom Typ cr2.data.PostgreTranslator sein. ähnelt.
        /// </summary>
        internal static string ERROR_MUSTBEPOSTGRETRANSLATOR {
            get {
                return ResourceManager.GetString("ERROR_MUSTBEPOSTGRETRANSLATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no active connection. ähnelt.
        /// </summary>
        internal static string ERROR_NOACTIVECONNECTION {
            get {
                return ResourceManager.GetString("ERROR_NOACTIVECONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no open connection to which a transaction can be created. ähnelt.
        /// </summary>
        internal static string ERROR_NOACTIVECONNECTION1 {
            get {
                return ResourceManager.GetString("ERROR_NOACTIVECONNECTION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no active transaction. ähnelt.
        /// </summary>
        internal static string ERROR_NOACTIVETRANSACTION {
            get {
                return ResourceManager.GetString("ERROR_NOACTIVETRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no open transaction. ähnelt.
        /// </summary>
        internal static string ERROR_NOACTIVETRANSACTION1 {
            get {
                return ResourceManager.GetString("ERROR_NOACTIVETRANSACTION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ {0} verfügt nicht über ein Feld mit dem Namen {1}. ähnelt.
        /// </summary>
        internal static string ERROR_NOFIELDINTYPE {
            get {
                return ResourceManager.GetString("ERROR_NOFIELDINTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Systemfelder sind nur erlaubt, wenn der Typ mit dem Attribut Table oder dem Attribut View versehen wurde. ähnelt.
        /// </summary>
        internal static string ERROR_NOSYSTEMFIELDSALLOWED {
            get {
                return ResourceManager.GetString("ERROR_NOSYSTEMFIELDSALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This method must be implemented in the concrete database connection class. ähnelt.
        /// </summary>
        internal static string ERROR_NOTIMPLEMENTEDINBASE {
            get {
                return ResourceManager.GetString("ERROR_NOTIMPLEMENTEDINBASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ {0} ist nicht serialisierbar. Das Objekt kann nicht serialisiert werden. ähnelt.
        /// </summary>
        internal static string ERROR_OBJECTNOTSERIALIZABLE {
            get {
                return ResourceManager.GetString("ERROR_OBJECTNOTSERIALIZABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while rollback transaction. See Innerexception for more informations. ähnelt.
        /// </summary>
        internal static string ERROR_ROLLBACKTRANSACTION {
            get {
                return ResourceManager.GetString("ERROR_ROLLBACKTRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Speichern wurde abgebrochen. ähnelt.
        /// </summary>
        internal static string ERROR_SAVECANCELED {
            get {
                return ResourceManager.GetString("ERROR_SAVECANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assembly konnte nicht erzeugt werden. ähnelt.
        /// </summary>
        internal static string ERROR_SCRIPTINGCANTCREATEASSEMBLY {
            get {
                return ResourceManager.GetString("ERROR_SCRIPTINGCANTCREATEASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Objekt der Klasse {0} konnte nicht erzeugt werden. ähnelt.
        /// </summary>
        internal static string ERROR_SCRIPTINGCANTCREATEOBJECT {
            get {
                return ResourceManager.GetString("ERROR_SCRIPTINGCANTCREATEOBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Fehler beim Compilieren der Assembly. ähnelt.
        /// </summary>
        internal static string ERROR_SCRIPTINGERRORWHILECOMPILEASSEMBLY {
            get {
                return ResourceManager.GetString("ERROR_SCRIPTINGERRORWHILECOMPILEASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Erzeugen der Assembly.
        ///{0} ähnelt.
        /// </summary>
        internal static string ERROR_SCRIPTINGERRORWHILECREATEASSEMBLY {
            get {
                return ResourceManager.GetString("ERROR_SCRIPTINGERRORWHILECREATEASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Erzeugen des Objektes.
        ///{0} ähnelt.
        /// </summary>
        internal static string ERROR_SCRIPTINGERRORWHILECREATEOBJECT {
            get {
                return ResourceManager.GetString("ERROR_SCRIPTINGERRORWHILECREATEOBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehlerhafte Maske: {0} ähnelt.
        /// </summary>
        internal static string ERROR_STRINGMASKERROR {
            get {
                return ResourceManager.GetString("ERROR_STRINGMASKERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für das Systemfeld {0} existiert bereits ein Feld für den Typen ({1}). Das Feld {2} kann daher nicht als Systemfeld für {0} definiert werden. ähnelt.
        /// </summary>
        internal static string ERROR_SYSTEMFIELDDUPLICATE {
            get {
                return ResourceManager.GetString("ERROR_SYSTEMFIELDDUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Systemfeld {0} kann nur ein einer Entitität vom Typ Table oder View verwendet werden. (die Klasse {1} muss mit dem Attribut Table oder View versehen werden) ähnelt.
        /// </summary>
        internal static string ERROR_SYSTEMFIELDNOTALLOWED {
            get {
                return ResourceManager.GetString("ERROR_SYSTEMFIELDNOTALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Systemfeld {0} muss als Persistant gekennzeichnet werden. ähnelt.
        /// </summary>
        internal static string ERROR_SYSTEMFIELDNOTMARKEDASPERSISTANT {
            get {
                return ResourceManager.GetString("ERROR_SYSTEMFIELDNOTMARKEDASPERSISTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die TableID der Tabelle {0} muss größer 0 sein ähnelt.
        /// </summary>
        internal static string ERROR_TABLEIDTOSMALL {
            get {
                return ResourceManager.GetString("ERROR_TABLEIDTOSMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ {0} enthält kein Feld mit dem Namen {1}. Regel kann nicht hinzugefügt werden. ähnelt.
        /// </summary>
        internal static string ERROR_TYPEDOESNTCONTAINFIELD {
            get {
                return ResourceManager.GetString("ERROR_TYPEDOESNTCONTAINFIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert darf nicht NULL sein. ähnelt.
        /// </summary>
        internal static string ERROR_VALUECANTBENULL {
            get {
                return ResourceManager.GetString("ERROR_VALUECANTBENULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert muss &gt;= 0 sein. ähnelt.
        /// </summary>
        internal static string ERROR_VALUEMUSTBEBIGGERTHENZERO {
            get {
                return ResourceManager.GetString("ERROR_VALUEMUSTBEBIGGERTHENZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ {0} kann nicht gleichzeitig als VIEW und als TABLE gekennzeichnet werden. ähnelt.
        /// </summary>
        internal static string ERROR_VIEWCANTBETABLE {
            get {
                return ResourceManager.GetString("ERROR_VIEWCANTBETABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Typ {0} der mit dem Attribut VIEW versehen wurde fehlt die Definition des Querys. Der Query des Views muss angegeben werden (wentweder über &apos;Query&apos; im Attribut View oder eine statische Methode &apos;RequestViewQuery&apos; in der Klasse des Typs. ähnelt.
        /// </summary>
        internal static string ERROR_VIEWDOENSTCONTAINQUERY {
            get {
                return ResourceManager.GetString("ERROR_VIEWDOENSTCONTAINQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Query des mit dem VIEW-Attribut versehenen Typs {0} fehlt der Platzhalter #FIELDS#, der die Felder repräsentiert, die abgefragt werden sollen. ähnelt.
        /// </summary>
        internal static string ERROR_VIEWDOESNTCONTAINFIELDS {
            get {
                return ResourceManager.GetString("ERROR_VIEWDOESNTCONTAINFIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Konvertieren des Bildes aus dem Datenstrom der Datenbank. ähnelt.
        /// </summary>
        internal static string ERROR_WHILECONVERTIMAGEFROMBYTEARRAY {
            get {
                return ResourceManager.GetString("ERROR_WHILECONVERTIMAGEFROMBYTEARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Konvertieren des Bildes in einen Datenstrom. ähnelt.
        /// </summary>
        internal static string ERROR_WHILECONVERTIMAGETOBYTEARRAY {
            get {
                return ResourceManager.GetString("ERROR_WHILECONVERTIMAGETOBYTEARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Konvertieren eines Wertes in das Datenbankformat. (Quelltyp: {0}, Zieltyp: {1}) ähnelt.
        /// </summary>
        internal static string ERROR_WHILETRANSLATINGTODB {
            get {
                return ResourceManager.GetString("ERROR_WHILETRANSLATINGTODB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Konvertieren eines Wertes aus dem Datenbankformat. (Quelltyp: {0}, Zieltyp: {1}) ähnelt.
        /// </summary>
        internal static string ERROR_WHILETRANSLATIONFROMDB {
            get {
                return ResourceManager.GetString("ERROR_WHILETRANSLATIONFROMDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Anlegen der Datenbank {0}. ähnelt.
        /// </summary>
        internal static string ERRORWHILECREATINGDATABASE {
            get {
                return ResourceManager.GetString("ERRORWHILECREATINGDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string some {
            get {
                return ResourceManager.GetString("some", resourceCulture);
            }
        }
    }
}
